name: Public IP

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
        
    - name: 🛒 Checkout
      uses: actions/checkout@v2
      
    - name: 🔎 Check IP
      run: curl https://api.ipify.org
