name: "Rollback1"

on: 
  release:
    types: [deleted]

jobs:
  deploy-on-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}
          path: .  # This will checkout the repository at the root level

      - name: Build and Check then Publish Production
        run: |
          cd ./.github/workflows/actions/rollback
          # Add your build and publish commands here
          run: sh rollback.yml  # Replace with the actual YAML file name

      - name: Deployed Production
        run: echo "Deployed Production"
