name: "Rollback1"

on: 
  release:
    types: [deleted]

jobs:
  deploy-on-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}

      - name: Check path
        run: |
          pwd
          ls
        
      #- name: Build and Check then Publish Production
      #  uses: ./.github/workflows/actions/rollback  # Replace with the correct path to your action.yml file

      - name: Deployed Production
        run: echo "Deployed Production"
        
  Deploy:
    needs: [deploy-on-release]
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Download Backend artifact
        uses: actions/download-artifact@v2
        with:
            name: backend-artifact
            path: backend-dist
          
      - name: Deploy Backend to IIS
        run: |
          cd backend-dist
          cd aspnet-core/src/CompanyWebsite.Web.Host
          dotnet publish CompanyWebsite.Web.Host.csproj --configuration Release --output ./publish /p:WebPublishMethod=MSDeploy /p:DeployIisAppPath="${{ secrets.IIS_NAME }}" /p:MSDeployServiceURL="${{ secrets.IIS_URL }}" /p:UserName="${{ secrets.IIS_USERNAME}}" /p:Password="${{ secrets.IIS_PASSWORD}}" /p:AllowUntrustedCertificate=true
  
