name: "Rollback1"

on: 
  release:
    types: [deleted]

jobs:
  deploy-on-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: check path
        run: |
          pwd
          ls
          
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Go to Path and Check
        run: cd ./.github/actions/rollback

      - name: Build and Check then Publish Production
        run: sh rollback.yml  # Replace with the actual YAML file name

      - name: Deployed Production
        run: echo "Deployed Production"
